-- Migration 094: Seed System Roles & Initial Permission Sets
-- Additive seed migration for Meet Commerce RBAC taxonomy (Blueprint §05.1, §05.2)

INSERT INTO roles (name, description, is_system, permissions) VALUES
  ('Super Admin', 'Full access to all platform features and administration', true,
   '["*"]'::jsonb),
  ('Admin', 'Platform administration and multi-vendor oversight', true,
   '["vendors.view","vendors.approve","vendors.suspend","product_proposals.approve","product_proposals.reject","warehouses.view","reports.global_view","reports.quality_view","reports.traceability_view"]'::jsonb),
  ('HQ Manager', 'Operations manager for vendor, catalogue, and fulfilment workflow', true,
   '["vendors.view","vendors.update","product_proposals.view","product_proposals.approve","procurement.view","procurement.create","reports.global_view"]'::jsonb),
  ('Support Agent', 'Customer and vendor support ticket handling and refunds', true,
   '["support_tickets.view","support_tickets.update","support_tickets.refund","support_tickets.replace","recalls.view"]'::jsonb),
  ('Finance User', 'Financial audit, settlement, payout management, and ledger review', true,
   '["finance.global_view","shop_financials.view","shop_financials.export","shop_financials.mark_paid","shop_transactions.view","shop_transactions.export","audit_logs.view"]'::jsonb),
  ('Content Manager', 'Catalogue curation, product proposal reviews, and marketing assets', true,
   '["product_proposals.view","product_proposals.approve","product_proposals.reject","shop_products.view","shop_products.approve"]'::jsonb),
  ('Marketing User', 'Coupons, promotions, banners, and loyalty program management', true,
   '["loyalty.view","loyalty.configure","loyalty.adjust","loyalty.export","shop_coupons.view","shop_coupons.create","shop_coupons.update","shop_coupons.delete"]'::jsonb),
  ('Read Only Analyst', 'Read-only access to global reports and operational analytics', true,
   '["reports.global_view","reports.quality_view","reports.traceability_view","shop_reports.view","inventory_ledger.view"]'::jsonb),
  ('Vendor Owner', 'Full control over vendor profile, staff, proposals, and supply batches', true,
   '["vendors.view","vendors.update","vendor_staff.view","vendor_staff.create","vendor_staff.update","vendor_staff.delete","vendor_documents.view","product_proposals.view","product_proposals.create","procurement.view","procurement.respond","supply_batches.view","supply_batches.create","supply_batches.update","batch_evidence.upload"]'::jsonb),
  ('Vendor Operator', 'Daily operations for vendor supply batches, evidence, and proposals', true,
   '["product_proposals.create","procurement.respond","supply_batches.view","supply_batches.create","supply_batches.update","batch_evidence.upload"]'::jsonb),
  ('Warehouse Receiver', 'Inbound supply batch intake and warehouse receipt creation', true,
   '["warehouse_receipts.view","warehouse_receipts.create","warehouse_receipts.update","warehouse_receipts.submit_qc","warehouses.view","supply_batches.view"]'::jsonb),
  ('Quality Controller', 'Meat and seafood quality control inspection and lab decisions', true,
   '["quality_control.view","quality_control.decide","quality_control.override","warehouse_receipts.view","supply_batches.view","batch_evidence.view"]'::jsonb),
  ('Picker', 'Order picking, weight verification, and lot allocation tasks', true,
   '["fulfilment.view","fulfilment.pick","inventory_lots.view"]'::jsonb),
  ('Packer', 'Order packing, cold chain temperature log, and barcode labeling', true,
   '["fulfilment.view","fulfilment.pack","inventory_lots.view"]'::jsonb),
  ('Inventory Manager', 'Lot management, FEFO adjustments, transfers, and recall triggers', true,
   '["inventory_lots.view","inventory_lots.adjust","inventory_lots.transfer","inventory_lots.recall","inventory_ledger.view","warehouses.view","recalls.create","recalls.activate"]'::jsonb),
  ('Rider', 'Cold-chain delivery tasks, shift management, and customer drop-off', true,
   '["delivery_tasks.update","riders.view","shop_orders.view"]'::jsonb),
  ('Customer', 'Customer ordering, address management, and loyalty rewards', true,
   '["shops.view","shop_products.view"]'::jsonb)
ON CONFLICT (name) DO NOTHING;
