export const ORDER_PREFIX = 'EXT60'

export const EXTENDED_CATEGORIES = [
  {
    name: 'Mobiles & Tablets',
    slug: 'mobiles-tablets',
    description: 'Smartphones, tablets, and everyday mobile technology.',
    sortOrder: 13,
  },
  {
    name: 'Audio & Wearables',
    slug: 'audio-wearables',
    description: 'TWS, headphones, neckbands, smartwatches, and wearables.',
    sortOrder: 14,
  },
  {
    name: 'Gadgets & Accessories',
    slug: 'gadgets-accessories',
    description: 'Chargers, power banks, cables, cases, and personal gadgets.',
    sortOrder: 15,
  },
  {
    name: 'Small Appliances',
    slug: 'small-appliances',
    description: 'Daily-use home appliances and countertop essentials.',
    sortOrder: 16,
  },
  {
    name: 'Fashion & Essentials',
    slug: 'fashion-essentials',
    description: 'Apparel, accessories, and wardrobe basics for daily wear.',
    sortOrder: 17,
  },
  {
    name: 'Cafe Specials',
    slug: 'cafe-specials',
    description: 'Fresh drinks, quick bites, and cafe-style treats.',
    sortOrder: 18,
  },
  {
    name: 'Dhaba Meals',
    slug: 'dhaba-meals',
    description: 'Comfort meals, Indian combos, and homestyle favourites.',
    sortOrder: 19,
  },
]

export const EXTENDED_CATEGORY_SLUGS = EXTENDED_CATEGORIES.map((category) => category.slug)

export const VENDORS = {
  electronics: {
    name: 'Bakaloo Electronics Fulfillment',
    address: 'Unit 12, Tech Logistics Park, Mahadevapura, Bengaluru, Karnataka 560048',
    fssai: null,
  },
  fashion: {
    name: 'Bakaloo Fashion Hub',
    address: 'Block C, Apparel Distribution Centre, HSR Layout, Bengaluru, Karnataka 560102',
    fssai: null,
  },
  kitchen: {
    name: 'Bakaloo Fresh Kitchen',
    address: 'Kitchen Bay 4, Food Hub, Koramangala Industrial Layout, Bengaluru, Karnataka 560095',
    fssai: '11223111001864',
  },
}

const techProduct = (config) => ({
  profile: 'tech',
  unit: 'piece',
  packType: config.packType ?? 'Retail box',
  storageInstructions: config.storageInstructions ?? 'Store in a cool, dry place away from heat and moisture.',
  returnPolicy: config.returnPolicy ?? '7_day',
  vendorKey: 'electronics',
  stockQuantity: config.stockQuantity ?? 40,
  maxOrderQty: config.maxOrderQty ?? 2,
  avgRating: config.avgRating ?? 4.4,
  ratingCount: config.ratingCount ?? 140,
  totalSold: config.totalSold ?? 320,
  isFeatured: config.isFeatured ?? false,
  seedReviewCount: config.seedReviewCount ?? 2,
  reviewLead: config.reviewLead ?? 'Good quality product and setup was straightforward',
  netQuantity: config.netQuantity ?? '1 unit',
  shelfLife: null,
  ingredients: null,
  allergenInfo: null,
  nutritionInfo: null,
  certifications: [],
  ...config,
  tags: Array.from(new Set(['electronics', 'super-mall', ...(config.tags ?? [])])),
})

const fashionProduct = (config) => ({
  profile: 'fashion',
  unit: config.unit ?? 'piece',
  packType: config.packType ?? 'Single piece pack',
  storageInstructions: config.storageInstructions ?? 'Store folded in a clean, dry place and follow wash-care instructions.',
  returnPolicy: config.returnPolicy ?? '7_day',
  vendorKey: 'fashion',
  stockQuantity: config.stockQuantity ?? 90,
  maxOrderQty: config.maxOrderQty ?? 3,
  avgRating: config.avgRating ?? 4.3,
  ratingCount: config.ratingCount ?? 110,
  totalSold: config.totalSold ?? 240,
  isFeatured: config.isFeatured ?? false,
  seedReviewCount: config.seedReviewCount ?? 2,
  reviewLead: config.reviewLead ?? 'The fit and material quality feel good for the price',
  shelfLife: null,
  ingredients: null,
  allergenInfo: null,
  nutritionInfo: null,
  certifications: [],
  ...config,
  tags: Array.from(new Set(['fashion', 'super-mall', ...(config.tags ?? [])])),
})

const cafeProduct = (config) => ({
  profile: 'food',
  unit: config.unit ?? 'cup',
  packType: config.packType ?? 'Ready-to-serve pack',
  storageInstructions: config.storageInstructions ?? 'Prepared fresh and best enjoyed immediately after delivery.',
  returnPolicy: 'no_return',
  vendorKey: 'kitchen',
  stockQuantity: config.stockQuantity ?? 50,
  maxOrderQty: config.maxOrderQty ?? 4,
  avgRating: config.avgRating ?? 4.4,
  ratingCount: config.ratingCount ?? 90,
  totalSold: config.totalSold ?? 170,
  isFeatured: config.isFeatured ?? false,
  seedReviewCount: config.seedReviewCount ?? 2,
  reviewLead: config.reviewLead ?? 'Fresh preparation and balanced flavour made it a good quick order',
  certifications: ['FSSAI'],
  ...config,
  tags: Array.from(new Set(['cafe', ...(config.tags ?? [])])),
})

const dhabaProduct = (config) => ({
  profile: 'food',
  unit: config.unit ?? 'plate',
  packType: config.packType ?? 'Meal tray',
  storageInstructions: config.storageInstructions ?? 'Prepared fresh and best consumed soon after delivery.',
  returnPolicy: 'no_return',
  vendorKey: 'kitchen',
  stockQuantity: config.stockQuantity ?? 45,
  maxOrderQty: config.maxOrderQty ?? 4,
  avgRating: config.avgRating ?? 4.5,
  ratingCount: config.ratingCount ?? 105,
  totalSold: config.totalSold ?? 210,
  isFeatured: config.isFeatured ?? false,
  seedReviewCount: config.seedReviewCount ?? 2,
  reviewLead: config.reviewLead ?? 'The meal arrived warm and had good portion value for the price',
  certifications: ['FSSAI'],
  ...config,
  tags: Array.from(new Set(['dhaba', ...(config.tags ?? [])])),
})

const mobiles = [
  techProduct({
    name: 'Apple iPhone 15 — 128GB',
    slug: 'apple-iphone-15-128gb',
    categorySlug: 'mobiles-tablets',
    brand: 'Apple',
    productType: 'smartphone',
    model: 'iPhone 15',
    variantLabel: 'Storage',
    variant: '128 GB',
    specLabel: 'Network',
    specValue: '5G',
    bestFor: 'daily communication, photography, and app-based work',
    price: 79900,
    salePrice: 74900,
    isFeatured: true,
    ratingCount: 482,
    avgRating: 4.7,
    totalSold: 860,
    tags: ['featured-launch'],
    reviewLead: 'The phone feels premium and performance stays smooth through the day',
  }),
  techProduct({
    name: 'Samsung Galaxy A55 5G — 8GB/128GB',
    slug: 'samsung-galaxy-a55-5g-8gb-128gb',
    categorySlug: 'mobiles-tablets',
    brand: 'Samsung',
    productType: 'smartphone',
    model: 'Galaxy A55 5G',
    variantLabel: 'Memory',
    variant: '8 GB / 128 GB',
    specLabel: 'Network',
    specValue: '5G',
    bestFor: 'everyday use, content streaming, and social media',
    price: 42999,
    salePrice: 38999,
    isFeatured: true,
    ratingCount: 336,
    avgRating: 4.6,
    totalSold: 620,
    reviewLead: 'Display quality is good and the phone handles daily tasks comfortably',
  }),
  techProduct({
    name: 'Redmi Note 13 5G — 6GB/128GB',
    slug: 'redmi-note-13-5g-6gb-128gb',
    categorySlug: 'mobiles-tablets',
    brand: 'Redmi',
    productType: 'smartphone',
    model: 'Note 13 5G',
    variantLabel: 'Memory',
    variant: '6 GB / 128 GB',
    specLabel: 'Network',
    specValue: '5G',
    bestFor: 'video streaming, browsing, and daily productivity',
    price: 19999,
    salePrice: 17999,
    ratingCount: 228,
    avgRating: 4.4,
    totalSold: 510,
    reviewLead: 'Good value smartphone and the day-to-day performance is dependable',
  }),
  techProduct({
    name: 'OnePlus Nord CE 4 Lite — 8GB/128GB',
    slug: 'oneplus-nord-ce-4-lite-8gb-128gb',
    categorySlug: 'mobiles-tablets',
    brand: 'OnePlus',
    productType: 'smartphone',
    model: 'Nord CE 4 Lite',
    variantLabel: 'Memory',
    variant: '8 GB / 128 GB',
    specLabel: 'Network',
    specValue: '5G',
    bestFor: 'multitasking, entertainment, and daily use',
    price: 22999,
    salePrice: 20999,
    ratingCount: 194,
    avgRating: 4.4,
    totalSold: 420,
    reviewLead: 'Clean day-to-day experience and the device feels balanced for regular use',
  }),
  techProduct({
    name: 'Apple iPad 10th Gen — 64GB Wi-Fi',
    slug: 'apple-ipad-10th-gen-64gb-wifi',
    categorySlug: 'mobiles-tablets',
    brand: 'Apple',
    productType: 'tablet',
    model: 'iPad 10th Gen',
    variantLabel: 'Storage',
    variant: '64 GB',
    specLabel: 'Connectivity',
    specValue: 'Wi-Fi',
    bestFor: 'study, note-taking, streaming, and casual work',
    price: 34900,
    salePrice: 32900,
    isFeatured: true,
    ratingCount: 168,
    avgRating: 4.6,
    totalSold: 288,
    reviewLead: 'Useful for study and streaming, and the overall tablet experience feels polished',
  }),
  techProduct({
    name: 'Samsung Galaxy Tab A9 — 64GB Wi-Fi',
    slug: 'samsung-galaxy-tab-a9-64gb-wifi',
    categorySlug: 'mobiles-tablets',
    brand: 'Samsung',
    productType: 'tablet',
    model: 'Galaxy Tab A9',
    variantLabel: 'Storage',
    variant: '64 GB',
    specLabel: 'Connectivity',
    specValue: 'Wi-Fi',
    bestFor: 'video calls, study sessions, and family entertainment',
    price: 16999,
    salePrice: 14999,
    ratingCount: 142,
    avgRating: 4.4,
    totalSold: 250,
    reviewLead: 'Compact tablet size and easy to use for browsing and video calls',
  }),
  techProduct({
    name: 'Motorola G85 5G — 8GB/128GB',
    slug: 'motorola-g85-5g-8gb-128gb',
    categorySlug: 'mobiles-tablets',
    brand: 'Motorola',
    productType: 'smartphone',
    model: 'G85 5G',
    variantLabel: 'Memory',
    variant: '8 GB / 128 GB',
    specLabel: 'Network',
    specValue: '5G',
    bestFor: 'daily calls, camera use, and app browsing',
    price: 21999,
    salePrice: 19999,
    ratingCount: 126,
    avgRating: 4.3,
    totalSold: 224,
    reviewLead: 'Smooth interface and a comfortable choice for regular daily usage',
  }),
  techProduct({
    name: 'realme Narzo 70 5G — 6GB/128GB',
    slug: 'realme-narzo-70-5g-6gb-128gb',
    categorySlug: 'mobiles-tablets',
    brand: 'realme',
    productType: 'smartphone',
    model: 'Narzo 70 5G',
    variantLabel: 'Memory',
    variant: '6 GB / 128 GB',
    specLabel: 'Network',
    specValue: '5G',
    bestFor: 'online classes, streaming, and social apps',
    price: 18999,
    salePrice: 16999,
    ratingCount: 118,
    avgRating: 4.3,
    totalSold: 202,
    reviewLead: 'Useful day-to-day phone and the value feels right at this price point',
  }),
  techProduct({
    name: 'Nokia T10 Tablet — 32GB Wi-Fi',
    slug: 'nokia-t10-tablet-32gb-wifi',
    categorySlug: 'mobiles-tablets',
    brand: 'Nokia',
    productType: 'tablet',
    model: 'T10',
    variantLabel: 'Storage',
    variant: '32 GB',
    specLabel: 'Connectivity',
    specValue: 'Wi-Fi',
    bestFor: 'light browsing, learning apps, and casual streaming',
    price: 11999,
    salePrice: 9999,
    ratingCount: 74,
    avgRating: 4.2,
    totalSold: 128,
    reviewLead: 'Basic tablet for casual use and simple entertainment needs',
  }),
  techProduct({
    name: 'POCO X6 5G — 8GB/256GB',
    slug: 'poco-x6-5g-8gb-256gb',
    categorySlug: 'mobiles-tablets',
    brand: 'POCO',
    productType: 'smartphone',
    model: 'X6 5G',
    variantLabel: 'Memory',
    variant: '8 GB / 256 GB',
    specLabel: 'Network',
    specValue: '5G',
    bestFor: 'heavy app use, gaming sessions, and entertainment',
    price: 24999,
    salePrice: 21999,
    ratingCount: 154,
    avgRating: 4.4,
    totalSold: 256,
    reviewLead: 'Strong everyday performance and enough storage for regular heavy users',
  }),
]

const audioWearables = [
  techProduct({
    name: 'boAt Airdopes 141 TWS',
    slug: 'boat-airdopes-141-tws',
    categorySlug: 'audio-wearables',
    brand: 'boAt',
    productType: 'true wireless earbuds',
    model: 'Airdopes 141',
    variantLabel: 'Playback Style',
    variant: 'Bluetooth TWS',
    specLabel: 'Use Case',
    specValue: 'music, calls, and commuting',
    bestFor: 'wireless music, calls, and travel',
    price: 1999,
    salePrice: 999,
    tags: ['half-price-store'],
    ratingCount: 264,
    avgRating: 4.3,
    totalSold: 590,
    reviewLead: 'Easy to pair and useful for casual listening through the day',
  }),
  techProduct({
    name: 'JBL Tune 770NC Headphones',
    slug: 'jbl-tune-770nc-headphones',
    categorySlug: 'audio-wearables',
    brand: 'JBL',
    productType: 'wireless headphones',
    model: 'Tune 770NC',
    variantLabel: 'Fit Type',
    variant: 'Over-ear',
    specLabel: 'Use Case',
    specValue: 'music, calls, and travel',
    bestFor: 'long listening sessions and office use',
    price: 9999,
    salePrice: 8499,
    isFeatured: true,
    ratingCount: 146,
    avgRating: 4.5,
    totalSold: 248,
    reviewLead: 'Comfortable fit and the sound profile works well for daily listening',
  }),
  techProduct({
    name: 'Noise ColorFit Pro 5 Smartwatch',
    slug: 'noise-colorfit-pro-5-smartwatch',
    categorySlug: 'audio-wearables',
    brand: 'Noise',
    productType: 'smartwatch',
    model: 'ColorFit Pro 5',
    variantLabel: 'Connectivity',
    variant: 'Bluetooth calling',
    specLabel: 'Use Case',
    specValue: 'fitness, notifications, and calls',
    bestFor: 'activity tracking and phone alerts',
    price: 4999,
    salePrice: 3499,
    ratingCount: 202,
    avgRating: 4.4,
    totalSold: 402,
    reviewLead: 'Watch setup is simple and the display works well for daily notifications',
  }),
  techProduct({
    name: 'boAt Rockerz 255 Pro+ Neckband',
    slug: 'boat-rockerz-255-pro-plus-neckband',
    categorySlug: 'audio-wearables',
    brand: 'boAt',
    productType: 'wireless neckband',
    model: 'Rockerz 255 Pro+',
    variantLabel: 'Connectivity',
    variant: 'Bluetooth neckband',
    specLabel: 'Use Case',
    specValue: 'calls and workouts',
    bestFor: 'hands-free calling and music on the go',
    price: 2299,
    salePrice: 1499,
    ratingCount: 180,
    avgRating: 4.3,
    totalSold: 370,
    reviewLead: 'Lightweight neckband and convenient for daily calls and workouts',
  }),
  techProduct({
    name: 'realme Buds T300',
    slug: 'realme-buds-t300',
    categorySlug: 'audio-wearables',
    brand: 'realme',
    productType: 'true wireless earbuds',
    model: 'Buds T300',
    variantLabel: 'Playback Style',
    variant: 'Bluetooth TWS',
    specLabel: 'Use Case',
    specValue: 'calls, streaming, and daily commute',
    bestFor: 'wireless listening and mobile calls',
    price: 2499,
    salePrice: 1999,
    ratingCount: 132,
    avgRating: 4.4,
    totalSold: 246,
    reviewLead: 'Compact pair of earbuds and convenient for everyday listening',
  }),
  techProduct({
    name: 'OnePlus Nord Buds 2r',
    slug: 'oneplus-nord-buds-2r',
    categorySlug: 'audio-wearables',
    brand: 'OnePlus',
    productType: 'true wireless earbuds',
    model: 'Nord Buds 2r',
    variantLabel: 'Playback Style',
    variant: 'Bluetooth TWS',
    specLabel: 'Use Case',
    specValue: 'calls, streaming, and workouts',
    bestFor: 'daily calls and casual listening',
    price: 2199,
    salePrice: 1799,
    ratingCount: 118,
    avgRating: 4.3,
    totalSold: 214,
    reviewLead: 'Comfortable for routine use and easy to keep paired through the day',
  }),
  techProduct({
    name: 'Fire-Boltt Ninja Call Pro Plus',
    slug: 'fire-boltt-ninja-call-pro-plus',
    categorySlug: 'audio-wearables',
    brand: 'Fire-Boltt',
    productType: 'smartwatch',
    model: 'Ninja Call Pro Plus',
    variantLabel: 'Connectivity',
    variant: 'Bluetooth calling',
    specLabel: 'Use Case',
    specValue: 'fitness and quick calling',
    bestFor: 'steps, alerts, and quick phone access',
    price: 3999,
    salePrice: 1999,
    tags: ['half-price-store'],
    ratingCount: 160,
    avgRating: 4.2,
    totalSold: 318,
    reviewLead: 'Useful budget smartwatch and the interface is easy to understand',
  }),
  techProduct({
    name: 'Sony MDR-ZX110A Wired Headphones',
    slug: 'sony-mdr-zx110a-wired-headphones',
    categorySlug: 'audio-wearables',
    brand: 'Sony',
    productType: 'wired headphones',
    model: 'MDR-ZX110A',
    variantLabel: 'Fit Type',
    variant: 'On-ear',
    specLabel: 'Use Case',
    specValue: 'calls, music, and laptop use',
    bestFor: 'desk listening and wired connectivity',
    price: 1490,
    salePrice: 1199,
    ratingCount: 96,
    avgRating: 4.3,
    totalSold: 172,
    reviewLead: 'Simple wired headphones and dependable for laptop and phone use',
  }),
]

const gadgetsAccessories = [
  techProduct({
    name: 'Apple 20W USB-C Power Adapter',
    slug: 'apple-20w-usb-c-power-adapter',
    categorySlug: 'gadgets-accessories',
    brand: 'Apple',
    productType: 'charging adapter',
    model: '20W USB-C Power Adapter',
    variantLabel: 'Power Output',
    variant: '20 W',
    specLabel: 'Connector Type',
    specValue: 'USB-C',
    bestFor: 'charging compatible phones and accessories',
    price: 1900,
    salePrice: 1699,
    ratingCount: 122,
    avgRating: 4.5,
    totalSold: 232,
    reviewLead: 'Compact charger and easy to carry for routine charging needs',
  }),
  techProduct({
    name: 'Samsung 25W Travel Adapter',
    slug: 'samsung-25w-travel-adapter',
    categorySlug: 'gadgets-accessories',
    brand: 'Samsung',
    productType: 'charging adapter',
    model: '25W Travel Adapter',
    variantLabel: 'Power Output',
    variant: '25 W',
    specLabel: 'Connector Type',
    specValue: 'USB-C',
    bestFor: 'charging smartphones and tablets',
    price: 1699,
    salePrice: 1399,
    ratingCount: 108,
    avgRating: 4.4,
    totalSold: 198,
    reviewLead: 'Solid everyday charger and the compact size is useful for travel',
  }),
  techProduct({
    name: 'boAt 10000mAh Power Bank',
    slug: 'boat-10000mah-power-bank',
    categorySlug: 'gadgets-accessories',
    brand: 'boAt',
    productType: 'power bank',
    model: '10000mAh Power Bank',
    variantLabel: 'Capacity',
    variant: '10000 mAh',
    specLabel: 'Use Case',
    specValue: 'travel and backup charging',
    bestFor: 'charging phones during commute and travel',
    price: 1999,
    salePrice: 999,
    tags: ['half-price-store'],
    ratingCount: 142,
    avgRating: 4.3,
    totalSold: 286,
    reviewLead: 'Handy backup charger and the size works well for travel bags',
  }),
  techProduct({
    name: 'Portronics Konnect Type-C Cable — 1m',
    slug: 'portronics-konnect-type-c-cable-1m',
    categorySlug: 'gadgets-accessories',
    brand: 'Portronics',
    productType: 'charging cable',
    model: 'Konnect',
    variantLabel: 'Cable Length',
    variant: '1 m',
    specLabel: 'Connector Type',
    specValue: 'USB-A to Type-C',
    bestFor: 'daily charging and desk setup use',
    price: 499,
    salePrice: 249,
    tags: ['half-price-store'],
    ratingCount: 88,
    avgRating: 4.2,
    totalSold: 164,
    reviewLead: 'Good utility cable and useful as a spare for everyday charging',
  }),
  techProduct({
    name: 'Spigen Liquid Air Case — iPhone 15',
    slug: 'spigen-liquid-air-case-iphone-15',
    categorySlug: 'gadgets-accessories',
    brand: 'Spigen',
    productType: 'phone case',
    model: 'Liquid Air',
    variantLabel: 'Compatibility',
    variant: 'iPhone 15',
    specLabel: 'Use Case',
    specValue: 'daily protection',
    bestFor: 'protecting the device during regular use',
    price: 1499,
    salePrice: 999,
    ratingCount: 72,
    avgRating: 4.4,
    totalSold: 118,
    reviewLead: 'Case fit feels secure and it keeps the phone comfortable to hold',
  }),
  techProduct({
    name: 'Logitech M221 Wireless Mouse',
    slug: 'logitech-m221-wireless-mouse',
    categorySlug: 'gadgets-accessories',
    brand: 'Logitech',
    productType: 'wireless mouse',
    model: 'M221',
    variantLabel: 'Connectivity',
    variant: 'Wireless USB receiver',
    specLabel: 'Use Case',
    specValue: 'office and laptop work',
    bestFor: 'desk work, study, and daily navigation',
    price: 1195,
    salePrice: 899,
    ratingCount: 126,
    avgRating: 4.5,
    totalSold: 210,
    reviewLead: 'Mouse is easy to set up and comfortable for long desk sessions',
  }),
  techProduct({
    name: 'HP K150 Wired Keyboard',
    slug: 'hp-k150-wired-keyboard',
    categorySlug: 'gadgets-accessories',
    brand: 'HP',
    productType: 'wired keyboard',
    model: 'K150',
    variantLabel: 'Connectivity',
    variant: 'USB wired',
    specLabel: 'Use Case',
    specValue: 'desktop and office work',
    bestFor: 'typing, office tasks, and study setups',
    price: 799,
    salePrice: 599,
    ratingCount: 84,
    avgRating: 4.3,
    totalSold: 156,
    reviewLead: 'Keyboard feels practical for regular work and basic home setup use',
  }),
  techProduct({
    name: 'Philips MultiGroom Trimmer — 7-in-1',
    slug: 'philips-multigroom-trimmer-7-in-1',
    categorySlug: 'gadgets-accessories',
    brand: 'Philips',
    productType: 'grooming trimmer',
    model: 'MultiGroom 7-in-1',
    variantLabel: 'Attachment Set',
    variant: '7-in-1 grooming kit',
    specLabel: 'Use Case',
    specValue: 'beard and body grooming',
    bestFor: 'home grooming and weekly maintenance',
    price: 2499,
    salePrice: 1899,
    ratingCount: 104,
    avgRating: 4.4,
    totalSold: 188,
    reviewLead: 'Useful grooming kit and easy to manage for routine self-care',
  }),
]

const smallAppliances = [
  techProduct({
    name: 'Philips Electric Kettle — 1.5L',
    slug: 'philips-electric-kettle-1-5l',
    categorySlug: 'small-appliances',
    brand: 'Philips',
    productType: 'electric kettle',
    model: 'Everyday Kettle',
    variantLabel: 'Capacity',
    variant: '1.5 L',
    specLabel: 'Use Case',
    specValue: 'boiling water and quick hot beverages',
    bestFor: 'tea, coffee, and quick kitchen prep',
    price: 2495,
    salePrice: 1999,
    ratingCount: 144,
    avgRating: 4.5,
    totalSold: 264,
    isFeatured: true,
    reviewLead: 'Handy kettle for routine use and the size works well for family tea breaks',
  }),
  techProduct({
    name: 'Prestige Sandwich Maker — 800W',
    slug: 'prestige-sandwich-maker-800w',
    categorySlug: 'small-appliances',
    brand: 'Prestige',
    productType: 'sandwich maker',
    model: 'Sandwich Maker',
    variantLabel: 'Power',
    variant: '800 W',
    specLabel: 'Use Case',
    specValue: 'grilled snacks and quick breakfasts',
    bestFor: 'toasting sandwiches and quick snacks',
    price: 2195,
    salePrice: 1799,
    ratingCount: 118,
    avgRating: 4.4,
    totalSold: 196,
    reviewLead: 'Useful for quick breakfasts and easy to keep in a compact kitchen',
  }),
  techProduct({
    name: 'Bajaj Rex Mixer Grinder — 500W',
    slug: 'bajaj-rex-mixer-grinder-500w',
    categorySlug: 'small-appliances',
    brand: 'Bajaj',
    productType: 'mixer grinder',
    model: 'Rex',
    variantLabel: 'Power',
    variant: '500 W',
    specLabel: 'Use Case',
    specValue: 'grinding spices and chutneys',
    bestFor: 'daily chutneys, masalas, and kitchen prep',
    price: 3399,
    salePrice: 2999,
    ratingCount: 132,
    avgRating: 4.3,
    totalSold: 212,
    reviewLead: 'Mixer is practical for routine kitchen prep and everyday grinding tasks',
  }),
  techProduct({
    name: 'Pigeon Induction Cooktop — 1800W',
    slug: 'pigeon-induction-cooktop-1800w',
    categorySlug: 'small-appliances',
    brand: 'Pigeon',
    productType: 'induction cooktop',
    model: 'Induction Cooktop',
    variantLabel: 'Power',
    variant: '1800 W',
    specLabel: 'Use Case',
    specValue: 'fast countertop cooking',
    bestFor: 'quick meals and compact kitchen setups',
    price: 3295,
    salePrice: 2799,
    ratingCount: 98,
    avgRating: 4.2,
    totalSold: 174,
    reviewLead: 'Good option for compact kitchens and fast everyday cooking needs',
  }),
  techProduct({
    name: 'Havells Dry Iron — 1000W',
    slug: 'havells-dry-iron-1000w',
    categorySlug: 'small-appliances',
    brand: 'Havells',
    productType: 'dry iron',
    model: 'Dry Iron',
    variantLabel: 'Power',
    variant: '1000 W',
    specLabel: 'Use Case',
    specValue: 'daily garment ironing',
    bestFor: 'regular clothing care and home ironing',
    price: 1699,
    salePrice: 1299,
    ratingCount: 86,
    avgRating: 4.2,
    totalSold: 148,
    reviewLead: 'Straightforward iron for regular use and everyday garment care',
  }),
  techProduct({
    name: 'Usha Quartz Room Heater — 800/1600W',
    slug: 'usha-quartz-room-heater-800-1600w',
    categorySlug: 'small-appliances',
    brand: 'Usha',
    productType: 'room heater',
    model: 'Quartz Room Heater',
    variantLabel: 'Power Modes',
    variant: '800 W / 1600 W',
    specLabel: 'Use Case',
    specValue: 'spot heating in cool weather',
    bestFor: 'small room heating and winter comfort',
    price: 2499,
    salePrice: 1999,
    ratingCount: 74,
    avgRating: 4.1,
    totalSold: 120,
    reviewLead: 'Useful seasonal heater and easy to place in a small room setup',
  }),
]

const fashion = [
  fashionProduct({
    name: "Levi's Solid Crew Neck T-Shirt",
    slug: 'levis-solid-crew-neck-tshirt',
    categorySlug: 'fashion-essentials',
    brand: "Levi's",
    productType: 't-shirt',
    netQuantity: '1 piece',
    material: 'Cotton blend',
    fit: 'Regular fit',
    variantLabel: 'Size',
    variant: 'M',
    bestFor: 'casual everyday wear',
    price: 1499,
    salePrice: 999,
    ratingCount: 142,
    avgRating: 4.4,
    totalSold: 276,
    reviewLead: 'Fabric feels comfortable and the tee works well for casual daily wear',
    careInstructions: 'Machine wash cold with like colours.',
  }),
  fashionProduct({
    name: 'Allen Solly Slim Fit Casual Shirt',
    slug: 'allen-solly-slim-fit-casual-shirt',
    categorySlug: 'fashion-essentials',
    brand: 'Allen Solly',
    productType: 'casual shirt',
    netQuantity: '1 piece',
    material: 'Cotton blend',
    fit: 'Slim fit',
    variantLabel: 'Size',
    variant: 'L',
    bestFor: 'smart casual office and weekend wear',
    price: 2199,
    salePrice: 1599,
    ratingCount: 98,
    avgRating: 4.3,
    totalSold: 182,
    reviewLead: 'Shirt looks neat on body and works for both office and casual use',
    careInstructions: 'Machine wash gently and dry in shade.',
  }),
  fashionProduct({
    name: 'U.S. Polo Assn. Polo T-Shirt',
    slug: 'us-polo-assn-polo-tshirt',
    categorySlug: 'fashion-essentials',
    brand: 'U.S. Polo Assn.',
    productType: 'polo t-shirt',
    netQuantity: '1 piece',
    material: 'Cotton pique',
    fit: 'Regular fit',
    variantLabel: 'Size',
    variant: 'M',
    bestFor: 'smart casual dressing and weekend wear',
    price: 1899,
    salePrice: 1399,
    ratingCount: 106,
    avgRating: 4.4,
    totalSold: 206,
    reviewLead: 'Polo feels versatile and easy to style for a clean casual look',
    careInstructions: 'Machine wash cold and iron on low heat if needed.',
  }),
  fashionProduct({
    name: 'Max Ankle Length Leggings',
    slug: 'max-ankle-length-leggings',
    categorySlug: 'fashion-essentials',
    brand: 'Max',
    productType: 'leggings',
    netQuantity: '1 piece',
    material: 'Cotton elastane blend',
    fit: 'Stretch fit',
    variantLabel: 'Size',
    variant: 'L',
    bestFor: 'daily wear and pairing with kurtas',
    price: 599,
    salePrice: 299,
    tags: ['half-price-store'],
    ratingCount: 132,
    avgRating: 4.3,
    totalSold: 258,
    reviewLead: 'Comfortable leggings and easy to pair with regular ethnic outfits',
    careInstructions: 'Machine wash with similar colours and dry flat.',
  }),
  fashionProduct({
    name: 'Biba Printed Kurta',
    slug: 'biba-printed-kurta',
    categorySlug: 'fashion-essentials',
    brand: 'Biba',
    productType: 'kurta',
    netQuantity: '1 piece',
    material: 'Cotton blend',
    fit: 'Straight fit',
    variantLabel: 'Size',
    variant: 'M',
    bestFor: 'ethnic day wear and festive casual styling',
    price: 2499,
    salePrice: 1799,
    ratingCount: 78,
    avgRating: 4.4,
    totalSold: 152,
    reviewLead: 'Print looks good and the kurta feels suitable for day-long wear',
    careInstructions: 'Wash gently and dry in shade to preserve print.',
  }),
  fashionProduct({
    name: 'Pepe Jeans Slim Fit Denim',
    slug: 'pepe-jeans-slim-fit-denim',
    categorySlug: 'fashion-essentials',
    brand: 'Pepe Jeans',
    productType: 'jeans',
    netQuantity: '1 piece',
    material: 'Cotton denim blend',
    fit: 'Slim fit',
    variantLabel: 'Waist Size',
    variant: '32',
    bestFor: 'casual denim styling and regular use',
    price: 2999,
    salePrice: 2299,
    ratingCount: 88,
    avgRating: 4.3,
    totalSold: 164,
    reviewLead: 'Denim feels sturdy and the fit works well for routine wear',
    careInstructions: 'Wash inside out and dry away from direct sun.',
  }),
  fashionProduct({
    name: 'Bakaloo Basics Cotton Joggers',
    slug: 'bakaloo-basics-cotton-joggers',
    categorySlug: 'fashion-essentials',
    brand: 'Bakaloo Basics',
    productType: 'joggers',
    netQuantity: '1 piece',
    material: 'Cotton terry blend',
    fit: 'Relaxed fit',
    variantLabel: 'Size',
    variant: 'L',
    bestFor: 'lounging, travel, and casual comfort',
    price: 999,
    salePrice: 699,
    ratingCount: 64,
    avgRating: 4.2,
    totalSold: 126,
    reviewLead: 'Soft joggers and comfortable enough for home and casual outings',
    careInstructions: 'Machine wash in cold water and tumble dry low.',
  }),
  fashionProduct({
    name: 'Jockey Cotton Socks — Pack of 3',
    slug: 'jockey-cotton-socks-pack-of-3',
    categorySlug: 'fashion-essentials',
    brand: 'Jockey',
    productType: 'socks',
    unit: 'pack',
    netQuantity: '3 pairs',
    material: 'Cotton blend',
    fit: 'Ankle length',
    variantLabel: 'Pack Size',
    variant: '3 pairs',
    bestFor: 'daily wear and regular commute use',
    price: 599,
    salePrice: 299,
    tags: ['half-price-store'],
    ratingCount: 92,
    avgRating: 4.4,
    totalSold: 204,
    reviewLead: 'Comfortable socks for daily use and the multi-pack feels useful',
    careInstructions: 'Machine wash with light colours and air dry.',
  }),
  fashionProduct({
    name: 'Fastrack Casual Cap',
    slug: 'fastrack-casual-cap',
    categorySlug: 'fashion-essentials',
    brand: 'Fastrack',
    productType: 'cap',
    netQuantity: '1 piece',
    material: 'Cotton twill',
    fit: 'Adjustable fit',
    variantLabel: 'Closure',
    variant: 'Adjustable back strap',
    bestFor: 'casual outdoor styling and travel',
    price: 799,
    salePrice: 399,
    tags: ['half-price-store'],
    ratingCount: 58,
    avgRating: 4.2,
    totalSold: 118,
    reviewLead: 'Cap fits well and works as a simple daily outdoor accessory',
    careInstructions: 'Spot clean gently and keep away from excess moisture.',
  }),
  fashionProduct({
    name: 'Wildcraft Bi-Fold Wallet',
    slug: 'wildcraft-bi-fold-wallet',
    categorySlug: 'fashion-essentials',
    brand: 'Wildcraft',
    productType: 'wallet',
    netQuantity: '1 piece',
    material: 'Synthetic leather',
    fit: 'Bi-fold format',
    variantLabel: 'Format',
    variant: 'Card and cash wallet',
    bestFor: 'daily carry and compact organisation',
    price: 999,
    salePrice: 699,
    ratingCount: 70,
    avgRating: 4.3,
    totalSold: 138,
    reviewLead: 'Wallet is compact and practical for routine daily use',
    careInstructions: 'Wipe clean with a soft dry cloth.',
  }),
]

const cafeSpecials = [
  cafeProduct({
    name: 'Bakaloo Cafe Cold Coffee — 300ml',
    slug: 'bakaloo-cafe-cold-coffee-300ml',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'cold coffee',
    netQuantity: '300 ml',
    variantLabel: 'Serving Style',
    variant: 'Chilled beverage',
    bestFor: 'quick refreshment and afternoon breaks',
    price: 149,
    salePrice: 129,
    unit: 'cup',
    isFeatured: true,
    tags: ['featured-launch'],
    ingredients: 'Milk, coffee blend, sugar, ice, and whipped topping.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed immediately',
    nutritionInfo: {
      'Energy (kcal)': '210',
      Protein: '6 g',
      Carbohydrate: '28 g',
      Fat: '8 g',
    },
    reviewLead: 'Refreshing cafe drink and the flavour balance works well for a quick break',
  }),
  cafeProduct({
    name: 'Bakaloo Cafe Iced Latte — 350ml',
    slug: 'bakaloo-cafe-iced-latte-350ml',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'iced latte',
    netQuantity: '350 ml',
    variantLabel: 'Serving Style',
    variant: 'Chilled milk coffee',
    bestFor: 'coffee breaks and daytime refreshment',
    price: 169,
    salePrice: 149,
    unit: 'cup',
    ingredients: 'Milk, espresso blend, ice, and sugar.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed immediately',
    nutritionInfo: {
      'Energy (kcal)': '180',
      Protein: '6 g',
      Carbohydrate: '20 g',
      Fat: '8 g',
    },
    reviewLead: 'Smooth chilled coffee and a good pick for a mid-day caffeine break',
  }),
  cafeProduct({
    name: 'Bakaloo Cafe Cappuccino — 250ml',
    slug: 'bakaloo-cafe-cappuccino-250ml',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'cappuccino',
    netQuantity: '250 ml',
    variantLabel: 'Serving Style',
    variant: 'Hot beverage',
    bestFor: 'coffee breaks and warm cafe-style sipping',
    price: 139,
    salePrice: 119,
    unit: 'cup',
    ingredients: 'Milk, espresso blend, and foam.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed hot on delivery',
    nutritionInfo: {
      'Energy (kcal)': '120',
      Protein: '5 g',
      Carbohydrate: '12 g',
      Fat: '5 g',
    },
    reviewLead: 'Good hot coffee option and the serving size feels right for one person',
  }),
  cafeProduct({
    name: 'Bakaloo Cafe Paneer Sandwich',
    slug: 'bakaloo-cafe-paneer-sandwich',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'sandwich',
    netQuantity: '1 serving',
    variantLabel: 'Filling',
    variant: 'Paneer and vegetables',
    bestFor: 'light meals and quick snacks',
    price: 199,
    salePrice: 169,
    unit: 'piece',
    ingredients: 'Bread, paneer, vegetables, seasoning, and sandwich spread.',
    allergenInfo: 'Contains milk and gluten.',
    shelfLife: 'Best consumed fresh',
    nutritionInfo: {
      'Energy (kcal)': '320',
      Protein: '13 g',
      Carbohydrate: '34 g',
      Fat: '14 g',
    },
    reviewLead: 'Fresh sandwich filling and a satisfying option for a quick meal',
  }),
  cafeProduct({
    name: 'Bakaloo Cafe Veg Wrap',
    slug: 'bakaloo-cafe-veg-wrap',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'wrap',
    netQuantity: '1 serving',
    variantLabel: 'Filling',
    variant: 'Mixed vegetables and sauce',
    bestFor: 'grab-and-go lunch and snack breaks',
    price: 189,
    salePrice: 159,
    unit: 'piece',
    ingredients: 'Flatbread, vegetables, sauce, and seasoning.',
    allergenInfo: 'Contains gluten.',
    shelfLife: 'Best consumed fresh',
    nutritionInfo: {
      'Energy (kcal)': '290',
      Protein: '7 g',
      Carbohydrate: '36 g',
      Fat: '12 g',
    },
    reviewLead: 'Wrap feels convenient for a quick meal and the portion is balanced',
  }),
  cafeProduct({
    name: 'Bakaloo Cafe Garlic Bread',
    slug: 'bakaloo-cafe-garlic-bread',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'garlic bread',
    netQuantity: '4 pieces',
    variantLabel: 'Serving Style',
    variant: 'Toasted slices',
    bestFor: 'sharing, snacking, and add-on cafe orders',
    price: 129,
    salePrice: 99,
    unit: 'plate',
    tags: ['half-price-store'],
    ingredients: 'Bread, garlic butter spread, herbs, and seasoning.',
    allergenInfo: 'Contains milk and gluten.',
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '260',
      Protein: '6 g',
      Carbohydrate: '30 g',
      Fat: '12 g',
    },
    reviewLead: 'Good crispy side option and a useful add-on for small cafe orders',
  }),
  cafeProduct({
    name: 'Bakaloo Cafe Chocolate Brownie',
    slug: 'bakaloo-cafe-chocolate-brownie',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'brownie',
    netQuantity: '1 piece',
    variantLabel: 'Serving Style',
    variant: 'Single dessert portion',
    bestFor: 'sweet cravings and dessert add-ons',
    price: 119,
    salePrice: 99,
    unit: 'piece',
    ingredients: 'Chocolate batter, flour, sugar, butter, and cocoa.',
    allergenInfo: 'Contains milk, egg, and gluten.',
    shelfLife: 'Best consumed on the day of delivery',
    nutritionInfo: {
      'Energy (kcal)': '280',
      Protein: '4 g',
      Carbohydrate: '32 g',
      Fat: '14 g',
    },
    reviewLead: 'Brownie tastes fresh and works well as a simple dessert order',
  }),
  cafeProduct({
    name: 'Bakaloo Cafe Blueberry Muffin',
    slug: 'bakaloo-cafe-blueberry-muffin',
    categorySlug: 'cafe-specials',
    brand: 'Bakaloo Cafe',
    productType: 'muffin',
    netQuantity: '1 piece',
    variantLabel: 'Flavour',
    variant: 'Blueberry',
    bestFor: 'tea-time and sweet snack breaks',
    price: 109,
    salePrice: 89,
    unit: 'piece',
    ingredients: 'Flour, sugar, butter, blueberry compote, and milk solids.',
    allergenInfo: 'Contains milk, egg, and gluten.',
    shelfLife: 'Best consumed on the day of delivery',
    nutritionInfo: {
      'Energy (kcal)': '250',
      Protein: '4 g',
      Carbohydrate: '30 g',
      Fat: '11 g',
    },
    reviewLead: 'Muffin is soft and works well for a light sweet snack',
  }),
]

const dhabaMeals = [
  dhabaProduct({
    name: 'Bakaloo Dhaba Rajma Chawal',
    slug: 'bakaloo-dhaba-rajma-chawal',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'meal bowl',
    netQuantity: '1 serving',
    variantLabel: 'Meal Style',
    variant: 'Rajma with steamed rice',
    bestFor: 'comfort lunch and filling meal breaks',
    price: 179,
    salePrice: 149,
    unit: 'bowl',
    isFeatured: true,
    tags: ['featured-launch'],
    ingredients: 'Rajma gravy, steamed rice, onion garnish, and seasoning.',
    allergenInfo: null,
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '410',
      Protein: '14 g',
      Carbohydrate: '62 g',
      Fat: '10 g',
    },
    reviewLead: 'Comforting meal bowl and the rice-to-gravy ratio feels satisfying',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Chole Chawal',
    slug: 'bakaloo-dhaba-chole-chawal',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'meal bowl',
    netQuantity: '1 serving',
    variantLabel: 'Meal Style',
    variant: 'Chole with steamed rice',
    bestFor: 'hearty lunch and homestyle North Indian meals',
    price: 179,
    salePrice: 149,
    unit: 'bowl',
    ingredients: 'Chole masala, steamed rice, onion garnish, and seasoning.',
    allergenInfo: null,
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '420',
      Protein: '13 g',
      Carbohydrate: '64 g',
      Fat: '10 g',
    },
    reviewLead: 'Good comfort meal and the chole flavour works well with the rice portion',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Dal Makhani Rice Bowl',
    slug: 'bakaloo-dhaba-dal-makhani-rice-bowl',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'meal bowl',
    netQuantity: '1 serving',
    variantLabel: 'Meal Style',
    variant: 'Dal makhani with rice',
    bestFor: 'comfort dinners and indulgent meal cravings',
    price: 189,
    salePrice: 159,
    unit: 'bowl',
    ingredients: 'Dal makhani, steamed rice, butter garnish, and spices.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '440',
      Protein: '15 g',
      Carbohydrate: '58 g',
      Fat: '14 g',
    },
    reviewLead: 'Rich gravy bowl and good option when you want a filling comfort meal',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Paneer Butter Masala Meal',
    slug: 'bakaloo-dhaba-paneer-butter-masala-meal',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'meal combo',
    netQuantity: '1 serving',
    variantLabel: 'Meal Style',
    variant: 'Paneer curry with rice and sides',
    bestFor: 'vegetarian meal orders and dinner combos',
    price: 229,
    salePrice: 199,
    unit: 'combo',
    ingredients: 'Paneer butter masala, jeera rice, salad, and seasoning.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '520',
      Protein: '18 g',
      Carbohydrate: '54 g',
      Fat: '24 g',
    },
    reviewLead: 'Paneer meal feels complete and works well for a satisfying one-person order',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Aloo Paratha Combo',
    slug: 'bakaloo-dhaba-aloo-paratha-combo',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'paratha combo',
    netQuantity: '2 parathas',
    variantLabel: 'Serving Style',
    variant: 'With curd and pickle',
    bestFor: 'breakfast orders and filling snack meals',
    price: 169,
    salePrice: 139,
    unit: 'combo',
    ingredients: 'Aloo paratha, curd cup, pickle, and butter.',
    allergenInfo: 'Contains milk and gluten.',
    shelfLife: 'Best consumed warm',
    nutritionInfo: {
      'Energy (kcal)': '460',
      Protein: '11 g',
      Carbohydrate: '56 g',
      Fat: '19 g',
    },
    reviewLead: 'Paratha combo feels filling and works well as a breakfast-style order',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Veg Thali',
    slug: 'bakaloo-dhaba-veg-thali',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'thali',
    netQuantity: '1 thali',
    variantLabel: 'Serving Style',
    variant: 'Curated veg meal platter',
    bestFor: 'balanced lunch and complete meal orders',
    price: 249,
    salePrice: 219,
    unit: 'plate',
    isFeatured: true,
    ingredients: 'Seasonal sabzi, dal, rice, roti, salad, and dessert portion.',
    allergenInfo: 'May contain milk and gluten.',
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '610',
      Protein: '18 g',
      Carbohydrate: '82 g',
      Fat: '22 g',
    },
    reviewLead: 'Thali portion feels complete and works well when you want a full meal',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Jeera Rice',
    slug: 'bakaloo-dhaba-jeera-rice',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'rice bowl',
    netQuantity: '1 serving',
    variantLabel: 'Serving Style',
    variant: 'Flavoured rice side',
    bestFor: 'pairing with curries and side meal orders',
    price: 119,
    salePrice: 99,
    unit: 'bowl',
    ingredients: 'Basmati rice, cumin, ghee, and seasoning.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '280',
      Protein: '5 g',
      Carbohydrate: '42 g',
      Fat: '9 g',
    },
    reviewLead: 'Rice portion is useful as a side and pairs well with curry-style meals',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Masala Chai Flask — 500ml',
    slug: 'bakaloo-dhaba-masala-chai-flask-500ml',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'tea flask',
    netQuantity: '500 ml',
    variantLabel: 'Serving Style',
    variant: 'Hot masala chai',
    bestFor: 'group tea breaks and sharing portions',
    price: 129,
    salePrice: 109,
    unit: 'flask',
    ingredients: 'Milk tea, sugar, tea leaves, and spice blend.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '180',
      Protein: '5 g',
      Carbohydrate: '24 g',
      Fat: '7 g',
    },
    reviewLead: 'Tea arrives hot and the flask size is useful for sharing',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Sweet Lassi — 300ml',
    slug: 'bakaloo-dhaba-sweet-lassi-300ml',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'lassi',
    netQuantity: '300 ml',
    variantLabel: 'Serving Style',
    variant: 'Chilled sweet lassi',
    bestFor: 'meal pairing and cooling refreshment',
    price: 99,
    salePrice: 79,
    unit: 'glass',
    ingredients: 'Curd, sugar, cardamom, and chilled water.',
    allergenInfo: 'Contains milk.',
    shelfLife: 'Best consumed chilled on delivery',
    nutritionInfo: {
      'Energy (kcal)': '190',
      Protein: '6 g',
      Carbohydrate: '26 g',
      Fat: '7 g',
    },
    reviewLead: 'Lassi feels refreshing and complements the meal nicely',
  }),
  dhabaProduct({
    name: 'Bakaloo Dhaba Kadhai Paneer Meal',
    slug: 'bakaloo-dhaba-kadhai-paneer-meal',
    categorySlug: 'dhaba-meals',
    brand: 'Bakaloo Dhaba',
    productType: 'meal combo',
    netQuantity: '1 serving',
    variantLabel: 'Meal Style',
    variant: 'Kadhai paneer with roti',
    bestFor: 'vegetarian dinner orders and rich curry meals',
    price: 239,
    salePrice: 209,
    unit: 'combo',
    ingredients: 'Kadhai paneer, rotis, onion salad, and seasoning.',
    allergenInfo: 'Contains milk and gluten.',
    shelfLife: 'Best consumed hot',
    nutritionInfo: {
      'Energy (kcal)': '540',
      Protein: '19 g',
      Carbohydrate: '48 g',
      Fat: '27 g',
    },
    reviewLead: 'Paneer meal tastes hearty and the combo portion is good for one person',
  }),
]

export const EXTENDED_PRODUCTS = [
  ...mobiles,
  ...audioWearables,
  ...gadgetsAccessories,
  ...smallAppliances,
  ...fashion,
  ...cafeSpecials,
  ...dhabaMeals,
]

export const EXTENDED_PRODUCT_SLUGS = EXTENDED_PRODUCTS.map((product) => product.slug)
